### ISSUE TITLE
v1.0.0.1 locks up

### ISSUE THREAD

**Issue by starbuck5250** [ChrisHird/FTPCLNT#8]
ADDLIBLE FTPCLNT

WRKCFGCCFG to set the defaults, press Enter.

FTPCLIENT
Host address ftp.software.ibm.com
Remote port 21
Userid / password anonymous
Remote directory /as400/pubs
Local directory /home/itmc
Transfer type BINARY
Connection retry 2
Connection delay 1

Option 1 to connect.
  Messages flash by
  Get break message `Cannot use program message queue *INVQ.`
  Get status message NOOP
  Press Enter - command line is locked up

Using another job, inspect the locked up job.
Call stack:
```
Type  Program                  Statement         Procedure    
      QCMD       QSYS                     /04FA               
      S          BUCK          9100       /0093               
   1  QCMD       QSYS                     /01C8               
      FTP801P    FTPCLNT                         _C_pep       
      FTP801P    FTPCLNT       14                main         
      FTP801P    FTPCLNT       41                AppWrkLclCwd 
      FTP801P    FTPCLNT       4                 snd_error_msg
      QMHSNDM    QSYS                     /0126               
      QMHSNSTQ   QSYS                     /0435               
      QWTPECTL   QSYS                     /0147               
      QMHDLVMS   QSYS                     /01B7               
      QMHDSMSS   QSYS                     /0B78               
      QWSGET     QSYS                     /0663               
      QT3REQIO   QSYS                     /0256                    
      FTP801P    FTPCLNT       1                 alarm_catcher     
      FTP801P    FTPCLNT       16                Check_Cntrl_Socket
      FTP801P    FTPCLNT       7                 Dsp_Server_Reply  
      QSOSRV1    QSYS          9                 recv              
```
Job log:
```
>> ftpclient                                                                
   Ownership of object FTPCLOGQ in QTEMP type *MSGQ changed.                
   Object FTPCLOGQ type *MSGQ created in library QTEMP.                     
   Space offset X'FFFFFFFF' or X'0000000000000000' is outside current limit 
     for object ITMC      ITMC      798014.                                 
   Application error.  MCH0601 unmonitored by FTP801P at statement          
      0000000122, instruction X'0000'.
    CPF2479 Call stack entry not found.       
Cause . . . . . :   Call stack entry QUIDSPP , specified for the send,   
  receive, move or delete message operation, could not be found in the ca
  stack.                                                                 
(Note, the stack entry name, QUIDSPP has a nondisplayable character at the end of it.)
```

Back to the locked up FTPCLIENT job
System request, 2 receive `CPF7121 End request is not allowed.`

90 to sign off works.

When I sign back on, I have a CPF6A43 from FTP801P `Cannot use program message queue *INVQ. `

Also, the file that is in the remote directory (400WhitePaper.pdf) is not transferred to my local system.

**Comment by ChrisHird** [comment]
Buck

 

OK I get the same error when connecting using anonymous. I will need to look and create fix. Please add as issue to GitHub if you could.

 

Chris…

**Comment by ChrisHird** [comment]
Problem is due to the layout of the list returned by the FTP Server. IBM i does not support all of the features other platforms do. I need to review the returned LIST replies to determine the best way to break down the list and place to the UIM panel.

Return Code 226-Options -l is not expected..

**Comment by ChrisHird** [comment]
Review EPLF format to see if it is returned by IBM i and other platforms (easier to decode).

**Comment by ChrisHird** [comment]
Resolved by improving the parse function which looped when total file list was returned as part of the LIST output.
